export const categories: Array<String> = [
  'Technology',
  'Travel',
  'Food and Cooking',
  'Health and Fitness',
  'Fashion',
  'Beauty and Skincare',
  'Lifestyle',
  'Parenting',
  'Finance and Money',
  'Business and Entrepreneurship',
  'Personal Development',
  'Education',
  'Arts and Culture',
  'Home and Decor',
  'Science',
  'Sports and Recreation',
  'Gaming',
  'Music',
  'Books and Literature',
  'Movies and TV Shows',
  'Cryptocurrency',
  'Blockchain',
  'Artificial Intelligence',
  'Data Science',
  'Cybersecurity',
  'Electronics',
];
